### ISSUE TITLE
Is is possible to get or record response status code?

### ISSUE THREAD

**Issue by dopin** [le0pard/mongodb_logger#64]
Hi, I have a question which I wrote in the title.
Is it possible? If so, how can I do that?
Could you ask me please?
Thank you.

**Comment by le0pard** [comment]
mongodb_logger logs only request information, but you can add additional info by `add_metadata` method. Example: 

`Rails.logger.add_metadata(user_id: current_user.id) if Rails.logger.respond_to?(:add_metadata)`

**Comment by dopin** [comment]
Thank you!

I could make it by doing this:

```ruby
after_action :log_response_code

def log_response_code
  Rails.logger.add_metadata(response_code: response.status)
end
```
