### ISSUE TITLE
Filter what to log to MongoDB

### ISSUE THREAD

**Issue by dmitrypol** [le0pard/mongodb_logger#65]
Is it possible to filter what gets logged to MongoDB?  I would like to only log messages with severity ERROR (exceptions). 

Or only requests to specific routes.  Or log different types of messages to different collections which can have different capped sizes / TTL indexes.  This way I can keep certain types of messages longer than others.

**Comment by le0pard** [comment]
Right now it is doesn't supported, but I am ready to accept PR.
